### PR TITLE
Fetch completion info from user progress bloc

### LINKED ISSUE #350: [BUG] - Learning actions in campaigns are not shown as completed until you leave and revisit the page.
**Describe the bug**
Learning actions in campaigns are not showing as completed once you've done them, until you leave the campaign page then reopen it

**To Reproduce**
1. Go to a campaigns page (e.g. Protect those in danger in Lebanon)
2. Click on a learning action (e.g. Reading What is happening in Lebanon?)
3. Read the article
4. Swipe to go back / click the cross
5. No change on the campaigns page (the learning action tick is still greyed out, as if you hadn't done it, until you close that campaign then reopen it, when the tick turns to green)

**Expected behavior**
I would expect the action to show as completed as soon as you return to the campaigns page

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7
 - OS: Android
 - App Version: Beta 2.0.20

### PR DESCRIPTION
**Pull request by JElgar**
# Description

Currently we store completion info inside resource models. This make its pretty hard to update after users complete more stuff which is what #350 is about. This pulls all completion/joined data from user progress bloc which is updated after each resource is completed and is therefore easy to keep up to date.

Fixes #350 

# Checklist:

## Creator

- [ ] The target branch is main
- [ ] I have updated the unreleased section of the change log
- [ ] I have reviewed the 'files changed' tab on github to ensure all changes are as expected
- [ ] I have added someone to review the pr

## Reviewer

- [ ] I have verified the above are all completed
- [ ] I have run the code locally to ensure it fufills the requirements of the issue
- [ ] I have reviewed the 'files changed' and commented on any sections which I think are not needed, incorrect or could be improved

## After pull

- [ ] If appropriate I have closed the issue/ moved the trello card

### CODE REVIEW

File: lib/models/action.dart [hunk 1]
```diff
@@ -144,14 +137,11 @@ class ListAction implements Explorable {
     required this.time,
     required BuiltList<Api.Cause> causes,
     required Api.ActionTypeEnum actionType,
-    required CausesUser? userInfo,
-  })  : cause = Cause.fromApiModel(causes[0], userInfo),
-        isCompleted = userInfo?.completedActionIds.contains(id) ?? false,
+  })  : cause = Cause.fromApiModel(causes[0]),
```
Comment (kackogut) [inline lib/models/action.dart:140]: Just a suggestion, doesn't Flutter have:
```suggestion
  })  : cause = Cause.fromApiModel(causes.first()),
```

File: lib/services/causes_service.dart [hunk 2]
```diff
@@ -93,11 +83,9 @@ class CausesService {
...
   /// Returns the Action with that id
   Future<Campaign> getCampaign(int id) async {
-    final (response, userInfo) = await (
-      _causeServiceClient.getCampaignsApi().campaignsRetrieve(id: id),
-      getUserInfo(),
-    ).wait;
-    return Campaign.fromApiModel(response.data!, userInfo);
+    final response =
+        await _causeServiceClient.getCampaignsApi().campaignsRetrieve(id: id);
+    return Campaign.fromApiModel(response.data!);
```
Comment (kackogut) [inline lib/services/causes_service.dart:88]: What if `response` will be `null`, shouldn't we return an error then?

File: lib/services/causes_service.dart [hunk 3]
```diff
@@ -106,14 +94,9 @@ class CausesService {
...
-      _causeServiceClient.getActionsApi().actionsRetrieve(id: id),
-      getUserInfo(),
-    ).wait;
-    return Action.fromApiModel(
-      response.data!,
-      userInfo,
-    );
+    final response =
+        await _causeServiceClient.getActionsApi().actionsRetrieve(id: id);
+    return Action.fromApiModel(response.data!);
```
Comment (kackogut) [inline lib/services/causes_service.dart:99]: Same here, no error handling, but it's already existing code, so not a blocker

File: lib/services/causes_service.dart [hunk 4]
```diff
@@ -93,11 +83,9 @@ class CausesService {
   /// Input Action id
   /// Returns the Action with that id
   Future<Campaign> getCampaign(int id) async {
-    final (response, userInfo) = await (
-      _causeServiceClient.getCampaignsApi().campaignsRetrieve(id: id),
-      getUserInfo(),
-    ).wait;
-    return Campaign.fromApiModel(response.data!, userInfo);
+    final response =
+        await _causeServiceClient.getCampaignsApi().campaignsRetrieve(id: id);
```
Comment (kackogut) [inline lib/services/causes_service.dart:87]: I think it's more of a preference, but for me this looks more readable than this line break:
```suggestion
    final response = await _causeServiceClient
        .getCampaignsApi()
        .campaignsRetrieve(id: id);
```

**Review by kackogut — APPROVED** [review]

File: lib/assets/components/explore_tiles.dart [hunk 5]
```diff
@@ -260,10 +263,17 @@ abstract class ExploreResourceTile extends ExploreTile {
...
-                    if (isCompleted != null)
-                      _ExploreTileCheckmark(
-                        completed: isCompleted!,
-                      ),
+                    BlocBuilder<UserProgressBloc, UserProgressState>(
+                      builder: (context, state) {
+                        final isComplete = getIsComplete(state);
+                        if (isComplete) {
+                          return _ExploreTileCheckmark(
+                            completed: isComplete,
```
[the remark this answers is not in the document]
Comment (JElgar) [reply lib/assets/components/explore_tiles.dart:271]: Yeah we had isCompleted as nullable before I think maybe because if the user was not logged in we treated it as null (no completion data) vs false (user has not competed this). 

For now we only use 2 states so ive just gone with a required bool

File: lib/services/causes_service.dart (hunk 2 above)
Comment (JElgar) [reply lib/services/causes_service.dart:88]: In theory an exception will get thrown which is caught a the bloc layer. I admit this isn't the best though. Do you think there is a clearer way of handling errors at the service level?

File: lib/services/causes_service.dart (hunk 4 above)
Comment (JElgar) [reply lib/services/causes_service.dart:87]: I agree but dartfmt doesn't seem to 😂. If I change this to what you suggested then dartfmt just changes it back...

Do you think there is a way we can configure this. From a very brief search it seems dart fmt does what it wants and you have very little say.

File: lib/main.dart [hunk 6]
```diff
@@ -126,6 +127,11 @@ class App extends StatelessWidget {
             )..fetchInternalNotifactions();
           },
         ),
+        BlocProvider(
+          create: (_) => UserProgressBloc(
+            causesService: locator<CausesService>(),
+          )..fetchUserState(),
```
[the remark this answers is not in the document]
Comment (JElgar) [reply lib/main.dart:133]: Ive renamed the `fetchUserState` to `init` is that what you are suggesting or is there some fancy bloc init thing i should be doing?

**Comment by JElgar** [comment]
Ive done a few tweaks but leaving the error handling and formatting comments for now as I think we need to discuss the best options
