### PR TITLE
Bugfix/image error handling

### LINKED ISSUE #148: [BUG] - NetworkImage crash
App crashing when NetworkImage error

### PR DESCRIPTION
**Pull request by JElgar**
https://trello.com/c/uHor6kAd/351-bug-high-app-closing-automatically
Fixes #148

### CODE REVIEW

**Comment by JElgar** [comment]
[BUG [high]: App closing automatically](https://trello.com/c/uHor6kAd/351-bug-high-app-closing-automatically)

File: test/setup/helpers/image_helpers.dart [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+
+}
+
+class MockHttpClient extends Mock implements HttpClient {}
+
+class MockHttpClientRequest extends Mock implements HttpClientRequest {}
+
+class MockHttpClientResponse extends Mock implements HttpClientResponse {}
+
+class MockHttpHeaders extends Mock implements HttpHeaders {}
```
Comment (JElgar) [inline test/setup/helpers/image_helpers.dart:56]: I think this can now all go?

File: test/widget_tests/image_test.dart [hunk 2]
```diff
@@ -0,0 +1,150 @@
...
+  tearDown(() {
+    cacheManager = null;
+  });
+
+  group("Custom network image tests - ", () {
+
+    // Tests taken from here
+    // https://github.com/Baseflow/flutter_cached_network_image/blob/develop/test/image_widget_test.dart    
+
+    // TODO Fix this test
```
Comment (JElgar) [inline test/widget_tests/image_test.dart:23]: Need to fix these 2 tests

**Review by JElgar — COMMENTED** [review]
Need to add tests for CachedImageProvider
